-- 관리자 화면


create TABLESPACE cookmaster
DATAFILE 'c:/oraclexe/data/cookmaster.dbf'
size 1m AUTOEXTEND on next 1k;

CREATE USER cookmaster IDENTIFIED BY 12341234
DEFAULT TABLESPACE cookmaster;

GRANT DBA TO cookmaster;


SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;
SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;

DROP TABLESPACE COOKDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;


drop user cookmaster cascade;